### ISSUE TITLE
XML esport server errore

### ISSUE THREAD

**Issue by humanurine** [mascor/erpnext_fattura_elettronica#35]
Hi,
I am just trying to adopt Erpnext for our company.
I am using a VM with this installed:
ERPNext: v9.1.3 (master)
Erpnext Fattura Elettronica: v0.0.1 (develop)
Frappe Framework: v9.1.5 (master

 I just tried the module for exporting an electronic invoice. I got this server error when I try to EXPORT EFE XML Report:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 53, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 923, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext_fattura_elettronica/erpnext_fattura_elettronica/erpnext_fattura_elettronica/doctype/efe_xml_export/efe_xml_export.py", line 40, in generate_electronic_invoices
    frappe.throw(ex)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 308, in msgprint
    message_log.append(json.dumps(out))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'Company' object has no attribute 'tax_id'",) is not JSON serializable

**Comment by gaurav-naik** [comment]
@humanurine Thanks for providing specifics about the ERPNext and Frappe versions. 

It appears that the tax_id field was added to the Company doctype in v10.

This app has been written on ERPNext v10, so it may not work correctly on v9.

**Comment by humanurine** [comment]
@gaurav-naik  Hi, thanks for your reply. Only an older Vm function for me. I downloaded the latest Production VM form erpnext website, but it does not work (tried in Deb and Ubuntu, no possibility to connect to localhost
Is there a different source forProduction VM?

**Comment by jimteamlinkt** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.
